
POST http://localhost:3001/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "email": "user@notfound.local",
  "name": "Keks",
  "password": "123456"
}

###

# Get user by ID
GET http://localhost:3000/api/auth/dbd6fbe5-1231-45e7-99cc-c07b048dc0eb HTTP/1.1

###

# Login user by email and password
POST http://localhost:3000/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "user@notfound.local",
  "password": "123456"
}

###
